# Generated by Django 4.1.3 on 2023-09-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='payment_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
